name: pinpin
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #image
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  equatable: ^2.0.5
  get_it: ^7.6.4
  injectable: ^2.3.2
  intl:
  auto_route: ^7.8.4
  either_dart: ^1.0.0
  freezed_annotation: ^2.4.1
  dio: ^5.7.0
  connectivity_plus: ^5.0.2
  image_picker: ^1.0.4
  pin_code_fields: ^8.0.1
  cloud_firestore: ^4.13.2
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  pull_to_refresh_flutter3: ^2.0.2
  firebase_storage: ^11.5.2
  pretty_dio_logger: ^1.3.1
  flutter_spinkit: ^5.2.0
  google_sign_in: ^6.1.6
  crypto: ^3.0.5
  flutter_facebook_auth: ^6.0.3
  url_launcher: ^6.3.0
  flutter_translate: ^4.1.0
  flutter_i18n: ^0.36.2
  flutter_secure_storage: ^9.2.2
  timeago: ^3.7.0
  dropdown_button2: ^2.3.9
  rxdart: ^0.28.0
  # chatview: ^2.2.0
  crypton: ^2.2.1
  emoji_picker_flutter: ^2.2.0
  any_link_preview: ^3.0.2
  audio_waveforms: ^1.0.5
  firebase_messaging: ^14.9.4
  flutter_keychain: ^2.5.0
  flutter_slidable: ^3.1.1
  encrypt: ^5.0.3
  device_info_plus: ^10.1.2
  rsa_encrypt: ^2.0.0
  dart_firebase_admin:
    git:
      url: https://github.com/leehoang21/dart_firebase_admin

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mocktail: ^1.0.1
  logger: ^2.0.2+1
  injectable_generator: ^2.4.1
  auto_route_generator: ^7.3.2
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  flutter_gen_runner: ^5.3.2
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
    - assets/i18n/
  
  fonts:
    - family: QS
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
  
flutter_gen:
  output: lib/common/assets/ # Optional (default: lib/gen/)

  # Optional
  integrations:
    flutter_svg: true


targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          explicit_to_json: true
          field_rename: snake