// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWHtNjtvo-mttYIYRUJldVM62q6QCc4Fo',
    appId: '1:7534333772:web:a123f766dbc291b85fc9e9',
    messagingSenderId: '7534333772',
    projectId: 'espend-b9ba9',
    authDomain: 'espend-b9ba9.firebaseapp.com',
    storageBucket: 'espend-b9ba9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP6z7OrwRk726VahwdxQhFKNb0KigFR9E',
    appId: '1:7534333772:android:1b20a5bb1d90280d5fc9e9',
    messagingSenderId: '7534333772',
    projectId: 'espend-b9ba9',
    storageBucket: 'espend-b9ba9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFKw6txIPr6cL_CqWV5Wt6D2UKYuw6RRo',
    appId: '1:7534333772:ios:9d551292cb664fb15fc9e9',
    messagingSenderId: '7534333772',
    projectId: 'espend-b9ba9',
    storageBucket: 'espend-b9ba9.appspot.com',
    iosBundleId: 'com.example.flutterESpend',
  );
}
