// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSHfgboYnJ9yjVxW-lsRObI89dTRbaJ-0',
    appId: '1:998896689837:web:0b870a97e8c7297d011c24',
    messagingSenderId: '998896689837',
    projectId: 'learning-english-6441b',
    authDomain: 'learning-english-6441b.firebaseapp.com',
    storageBucket: 'learning-english-6441b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2X8t-GU6tO74CXwuP8qQt7ZEG01fnJJ0',
    appId: '1:998896689837:android:18f44ca106a1d841011c24',
    messagingSenderId: '998896689837',
    projectId: 'learning-english-6441b',
    storageBucket: 'learning-english-6441b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDctFqwTuyu9nqU1xgf-Xaw8UGpOrr_jTM',
    appId: '1:998896689837:ios:baeb288a0d5405cc011c24',
    messagingSenderId: '998896689837',
    projectId: 'learning-english-6441b',
    storageBucket: 'learning-english-6441b.appspot.com',
    iosBundleId: 'vn.vanh.pin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSHfgboYnJ9yjVxW-lsRObI89dTRbaJ-0',
    appId: '1:998896689837:web:319ac029596dff9a011c24',
    messagingSenderId: '998896689837',
    projectId: 'learning-english-6441b',
    authDomain: 'learning-english-6441b.firebaseapp.com',
    storageBucket: 'learning-english-6441b.appspot.com',
  );

}